# Generated by Django 4.2 on 2026-03-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255)),
                ('ptype', models.CharField(max_length=255)),
                ('pprice', models.CharField(max_length=255)),
                ('p_photo', models.ImageField(upload_to='product_photo')),
                ('pdescription', models.TextField()),
            ],
        ),
    ]
