# Generated by Django 4.2 on 2026-03-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.BigIntegerField()),
                ('password', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='user_photo')),
                ('address', models.TextField()),
            ],
        ),
    ]
