# Generated by Django 4.2 on 2026-03-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_emailid', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('ptype', models.CharField(max_length=255)),
                ('pprice', models.CharField(max_length=255)),
                ('p_photo', models.TextField()),
                ('pdescription', models.TextField()),
                ('qunatity', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
    ]
