# Generated by Django 4.2 on 2026-03-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0002_user_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_order',
            name='order_shipped_status',
            field=models.TextField(default='Not Now'),
        ),
    ]
