# Generated by Django 4.2 on 2026-03-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0003_user_order_order_shipped_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_order',
            name='pname',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
