# Generated by Django 4.2 on 2026-03-22 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0004_user_order_pname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
